import os
import sys
from flask import send_from_directory

# Add current directory to path so we can import 'app'
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from app import app

# Configuration for Production
# Point to the 'dist' folder generated by 'npm run build'
FRONTEND_DIST = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'frontend', 'dist')

print(f"Serving Frontend from: {FRONTEND_DIST}")

@app.route('/', defaults={'path': ''})
@app.route('/<path:path>')
def serve(path):
    # Check if path exists in dist folder
    if path != "" and os.path.exists(os.path.join(FRONTEND_DIST, path)):
        return send_from_directory(FRONTEND_DIST, path)
    else:
        # Fallback to index.html for SPA routing (and root)
        return send_from_directory(FRONTEND_DIST, 'index.html')

if __name__ == '__main__':
    from waitress import serve
    print("Starting Production Server on http://localhost:5000")
    print("Press Ctrl+C to stop.")
    serve(app, host='0.0.0.0', port=5000)
